### ISSUE TITLE
Unable to build fuse

### ISSUE THREAD

**Issue by jesusrw** [jboss-fuse/fuse#119]
I've cloned the repo from master 
then  I try with :
- mvn -Pesb clean install
- mvn clean install
- mvn -Pamq clean install
- try using maven without setting.xml

still no joy what am I missing??
this is what Im using:

```
Apache Maven 3.3.1 
Maven home: c:\Java\apache-maven-3.3.1
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: c:\Java\Jdk7\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2012 r2", version: "6.3", arch: "amd64", family: "windows"
```

and this is the error

``` java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (unix-bin) on project jboss-a-mq: Failed to create assembly: File to filter not found: c:\ESB\fuse6.2\mq\mq-as
sembly\jboss-a-mq\.\target\META-INF\NOTICE (The system cannot find the path specified) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (unix-bin) on project jboss-a-mq: Failed to create assembly: F
ile to filter not found: c:\ESB\fuse6.2\mq\mq-assembly\jboss-a-mq\.\target\META-INF\NOTICE (The system cannot find the path specified)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: File to filter not found: c:\ESB\fuse6.2\mq\mq-assembly\jboss-a-mq\.\target\META-INF\NOTICE (The system cannot fi
nd the path specified)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:499)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: org.apache.maven.plugin.assembly.format.AssemblyFormattingException: File to filter not found: c:\ESB\fuse6.2\mq\mq-assembly\jboss-a-mq\.\target\META-INF\NOTICE (The system cannot find the
 path specified)
        at org.apache.maven.plugin.assembly.format.FileFormatter.formatLineEndings(FileFormatter.java:137)
        at org.apache.maven.plugin.assembly.format.FileFormatter.format(FileFormatter.java:82)
        at org.apache.maven.plugin.assembly.format.FileFormatter.format(FileFormatter.java:59)
        at org.apache.maven.plugin.assembly.archive.phase.FileItemAssemblyPhase.execute(FileItemAssemblyPhase.java:80)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:183)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:436)
        ... 22 more
Caused by: java.io.FileNotFoundException: c:\ESB\fuse6.2\mq\mq-assembly\jboss-a-mq\.\target\META-INF\NOTICE (The system cannot find the path specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at org.apache.maven.plugin.assembly.format.FileFormatter.formatLineEndings(FileFormatter.java:126)
        ... 27 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by xploumis** [comment]
Use Maven version 3.0.4

http://archive.apache.org/dist/maven/maven-3/3.0.4/binaries/

**Comment by davsclaus** [comment]
closing old ticket
