### ISSUE TITLE
Fuse startup error

### ISSUE THREAD

**Issue by sobkowiak** [jboss-fuse/fuse#19]
I'm trying to start fuse and getting following error

```
Please wait while JBoss Fuse is loading...
Bundle listed in startup.properties configuration not found: org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.jar
Could not create framework: java.lang.Exception: Aborting due to missing startup bundles
java.lang.Exception: Aborting due to missing startup bundles
    at org.apache.karaf.main.Main.processConfigurationProperties(Main.java:1249)
    at org.apache.karaf.main.Main.loadStartupProperties(Main.java:1062)
    at org.apache.karaf.main.Main.launch(Main.java:343)
    at org.apache.karaf.main.Main.main(Main.java:555)
```

**Comment by davsclaus** [comment]
closing old ticket
