### ISSUE TITLE
Can't start container - duplicate features

### ISSUE THREAD

**Issue by sabikla** [jboss-fuse/fuse#264]
It shows the following Provision Status:

error - java.lang.IllegalStateException: Duplicate feature found: openjpa/2.3.0

```
Provision Exception:
java.lang.IllegalStateException: Duplicate feature found: openjpa/2.3.0
  at io.fabric8.agent.service.Agent.provision(Agent.java:194)
  at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:727)
  at io.fabric8.agent.DeploymentAgent$4.run(DeploymentAgent.java:283)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

fuse console list the openjpa multipletimes
JBossFuse:karaf@root> features:list | grep openjpa
[uninstalled] [2.3.0                ] openjpa                                 karaf-enterprise-2.4.0.redhat-621084      
[uninstalled] [2.3.0                ] openjpa                                 repo-0                                      
[uninstalled] [2.3.0                ] openjpa                                 repo-0

**Comment by paoloantinori** [comment]
hi, please use JIRA or RH official support to track JBoss Fuse Issue:

https://issues.jboss.org/projects/ENTESB/summary
